### 모델 평가 및 검증 과제

---
- 다음의 자료를 가지고 간단히 모델 평가를 해보는 과제입니다.
- 맨 마지막 변수인 Class를 예측하는 것이 목표입니다.
---

In [27]:
from sklearn.model_selection import train_test_split
import pandas as pd

df = pd.read_csv("/Users/yumunsang/Documents/2018summer/boaz/boaz_hw/hw5_model_validation/fraud_data.csv") # path를 바꿔주세요.
df.head()



V1        V2        V3        V4        V5        V6        V7  \
0  1.176563  0.323798  0.536927  1.047002 -0.368652 -0.728586  0.084678   
1  0.681109 -3.934776 -3.801827 -1.147468 -0.735540 -0.501097  1.038865   
2  1.140729  0.453484  0.247010  2.383132  0.343287  0.432804  0.093380   
3 -1.107073 -3.298902 -0.184092 -1.795744  2.137564 -1.684992 -2.015606   
4 -0.314818  0.866839 -0.124577 -0.627638  2.651762  3.428128  0.194637   

         V8        V9       V10  ...         V21       V22       V23  \
0 -0.069246 -0.266389  0.155315  ...   -0.109627 -0.341365  0.057845   
1 -0.626979 -2.274423  1.527782  ...    0.652202  0.272684 -0.982151   
2  0.173310 -0.808999  0.775436  ...   -0.003802  0.058556 -0.121177   
3 -0.007181 -0.165760  0.869659  ...    0.130648  0.329445  0.927656   
4  0.670674 -0.442658  0.133499  ...   -0.312774 -0.799494 -0.064488   

        V24       V25       V26       V27       V28  Amount  Class  
0  0.499180  0.415211 -0.581949  0.015472  0.018065    4.67      0  
1  0.165900  0.360251  0.195321 -0.256273  0.056501  912.00      0  
2 -0.304215  0.645893  0.122600 -0.012115 -0.005945    1.00      0  
3 -0.049560 -1.892866 -0.575431  0.266573  0.414184   62.10      0  
4  0.953062 -0.429550  0.158225  0.076943 -0.015051    2.67      0  

[5 rows x 30 columns]

In [28]:
X = df.iloc[0,[0,1]]
X

V1    1.176563
V2    0.323798
Name: 0, dtype: float64

In [35]:
# X와 y를 나누기 위해 아래 []안의 조건을 넣어보세요.
X = df.iloc[:,0:29].values
y = df.iloc[:,29].values

# 이제 X와 y를 train, test set로 나눠보세요. (모두의 결과물이 같기 위해 random state는 0으로 해주세요.)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [36]:
X

array([[ 1.17656255e+00,  3.23797640e-01,  5.36927047e-01, ...,
         1.54721345e-02,  1.80650395e-02,  4.67000000e+00],
       [ 6.81109486e-01, -3.93477632e+00, -3.80182745e+00, ...,
        -2.56272932e-01,  5.65009045e-02,  9.12000000e+02],
       [ 1.14072867e+00,  4.53483633e-01,  2.47010003e-01, ...,
        -1.21148194e-02, -5.94502519e-03,  1.00000000e+00],
       ...,
       [-2.17516167e+00, -4.41681440e-01,  1.88313689e+00, ...,
         4.33089084e-01, -1.50290873e-01,  1.31100000e+02],
       [ 3.14062618e-02,  6.94816666e-01,  8.32325026e-02, ...,
         2.32845962e-01,  7.94200575e-02,  4.49000000e+00],
       [-3.12369468e-01,  9.44737713e-01,  1.43060545e+00, ...,
         2.32375299e-01, -2.35628647e-02,  1.49000000e+01]])

In [37]:
X_test

array([[ 8.66891521e-01, -8.99855707e-01,  9.71689866e-01, ...,
        -2.92684464e-02,  1.54136135e-02,  1.19210000e+02],
       [-2.44395906e+00, -3.32079263e+00,  1.03845897e+00, ...,
         3.85017852e-01,  3.12006395e-02,  9.92420000e+02],
       [ 2.06600812e+00,  2.12733685e-01, -1.67667616e+00, ...,
        -5.38974367e-02, -2.90450111e-02,  1.29000000e+00],
       ...,
       [ 1.39235347e+00, -1.17006906e+00, -2.10143887e+00, ...,
        -1.57313976e-01, -2.88104146e-02,  3.50490000e+02],
       [-1.13522915e+00, -4.72115345e-01,  1.27044789e+00, ...,
         1.33166688e-01,  1.38159362e-01,  1.00000000e+00],
       [ 1.13762164e+00,  1.74313403e-01,  4.04251406e-01, ...,
         3.12983150e-02,  2.61300060e-02,  3.13100000e+01]])

---
- dummy classifier를 학습시켜 무조건 샘플 숫자가 더 많은 경우로 예측하도록 해보세요. accuracy와 recall도 구해보세요.

- 함수의 결과물은 다음과 같아야 합니다: `(accuracy score, recall score)`
---

In [38]:
def first():
    from sklearn.dummy import DummyClassifier
    from sklearn.metrics import recall_score
    
    # 이곳에만 코드를 채우시면 됩니다.
    clf = DummyClassifier(random_state=0)
    clf.fit(X_train, y_train) # 이곳은 건드릴 필요X
    predictions = clf.predict(X_test)
    score = clf.score(X_test,y_test)
    recall_score = recall_score(y_test,predictions)
    
    return score, recall_score # 정답 리턴

first()

(0.9708702064896755, 0.0125)

---
- SVC classifer를 default parameters로 세팅하고(옵션 건드릴 필요 X) 모델의 accuracy, recall, 그리고 precision을 측정해보세요. 

- 함수의 결과물은 다음과 같아야 합니다: `(accuracy score, recall score, precision score)`
---

In [39]:
def second():
    from sklearn.metrics import recall_score, precision_score
    from sklearn.svm import SVC

    # 이곳에만 코드를 채우시면 됩니다.
    clf = SVC()
    clf.fit(X_train, y_train) # 이곳은 건드릴 필요X
    predictions = clf.predict(X_test)
    score = clf.score(X_test,y_test)
    recall_score = recall_score(y_test,predictions)
    precision_score = precision_score(y_test,predictions)
    
    return score, recall_score, precision_score # 정답 리턴

second()

(0.9907817109144543, 0.375, 1.0)

---
- SVC classifier의 옵션을 `{'C': 1e9, 'gamma': 1e-07}`으로 설정했을 떄
- decision function의 threshold를 -220으로 두었다면 confusion matrix는 어떻게 출력될까요?
- X-test와 y_test를 활용하세요.

- 함수는 2X2의 numpy array 형태, 즉 2X2의 confusion matrix를 출력해야 합니다.
---

In [40]:
def third():
    from sklearn.metrics import confusion_matrix
    from sklearn.svm import SVC

    # 이곳에만 코드를 채우시면 됩니다.
    clf = SVC()
    clf.fit(X_train, y_train) # 이곳은 건드릴 필요X
    y_scores = clf.predict(X_test)
    confusion_matrix = confusion_matrix(y_test,y_scores)

    return confusion_matrix # 정답 리턴

third()

array([[5344,    0],
       [  50,   30]])